services:
  - type: web
    name: video-sorter-bot
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false  # This will be set manually in Render dashboard
      - key: LOG_CHANNEL_ID
        value: "-1003057761446"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "10000"
    autoDeploy: true
    buildFilter:
      paths:
        - main.py
        - requirements.txt
        - render.yaml
